name: Android Release

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers on version tags like v1.0.0, v2.0.1, etc.

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Set up JDK
        uses: actions/setup-java@v4.5.0
        with:
          distribution: 'temurin'  # Can use 'adopt' as well
          java-version: '17'    # Set Java version to 17

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          name: Sounds_${{ github.ref_name }}.apk
          path: app/build/outputs/apk/release/*.apk
